spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: h.elcin78
    url: jdbc:postgresql://localhost:5432/trading-ms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect